# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 22:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ChitChat', '0002_auto_20160906_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='st',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
